image:
  repository: bitnami/spark
  tag: 3.5.0

sparkConf:
  "spark.sql.catalog.glue_catalog": "org.apache.iceberg.spark.SparkCatalog"
  "spark.sql.catalog.glue_catalog.type": "glue"
  "spark.sql.catalog.glue_catalog.warehouse": "s3a://your-bucket/warehouse/"
  "spark.sql.extensions": "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions"
  "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
  "spark.hadoop.fs.s3a.aws.credentials.provider": "com.amazonaws.auth.DefaultAWSCredentialsProviderChain"
  "spark.sql.catalog.glue_catalog.catalog-impl": "org.apache.iceberg.aws.glue.GlueCatalog"
  "spark.sql.catalog.glue_catalog.io-impl": "org.apache.iceberg.aws.s3.S3FileIO"
  "spark.sql.catalog.glue_catalog.lock-impl": "org.apache.iceberg.aws.glue.DynamoLockManager"
  "spark.sql.catalog.glue_catalog.lock.table": "hive_glue_catalog_locks"

serviceAccount:
  create: true

worker:
  replicas: 3
  resources:
    requests:
      memory: "3Gi"
      cpu: "1"
    limits:
      memory: "3Gi"
      cpu: "2"

master:
  service:
    type: LoadBalancer
